### ISSUE TITLE
Gestion des titres

### ISSUE THREAD

**Issue by luce-carevic** [empreinte-digitale/assistant-rgaa#18]
# Titre h1 manquant

**Comportement actuel :**  
L'assistant remonte en erreur une arborescence qui ne commence pas par un titre `<h1>`.

**Comportement attendu :**
Il n'est pas obligatoire de commencer une hiérarchie de titres par un titre `<h1>`. Cela ne doit donc pas remonter en erreur.

# Role heading et aria-level

Sur les titres, l'assistant ne gère pas les cas suivants : 

![2021-07-22-13 23 05@2x](https://user-images.githubusercontent.com/6073336/126631769-a2094c45-7b84-4627-94ec-8acc981c3cab.png)

![2021-07-22-13 24 58@2x](https://user-images.githubusercontent.com/6073336/126631936-0e21e307-4a92-43b8-bb3d-a53ca50c0338.png)

**Comportement actuel :** 
- présence d'un role="heading" sans préciser le niveau avec aria-level : l'élément n'est pas signalé comme étant un titre ;
- présence d'un aria-level sur un titre (hx) sans role heading : le bon niveau de titre n'est pas restitué ;

**Comportement attendu**

- Par défaut, si le niveau n'est pas précisé, le niveau de titre attendu est 2. cf. https://www.w3.org/TR/wai-aria-1.1/#heading
- Le role heading étant superflu sur un titre hx, on peut donc avoir des cas d'implémentations avec un aria-level uniquement. Il faut donc le prendre en compte et restituer le bon niveau de titre.

**Comment by felixgirault** [comment]
Merci pour ce retour détaillé !
Un dernier cas me pose question pour bien couvrir toutes les possibilités : 
```html
<h3 role="heading">Titre</h3>
```
Ce serait considéré comme un niveau 3 ? Ou plutôt 2 en supposant que l'attribut rôle écrase la sémantique initiale du h3 ? Auquel cas ce serait équivalent à `div[role="heading"]`, donc 2 par défaut.

**Comment by felixgirault** [comment]
Il semble aussi qu'actuellement des balises comme `<span aria-level="1">` soient considérées comme des titres :thinking:

**Comment by luce-carevic** [comment]
Ça reste bien un titre de niveau 3, car le h3 a déjà une sémantique de titre et donc le role="heading" seul n'écrase pas le niveau.

Je peux pas vérifier sur toute la base de réf actuellement la restitution, mais ça devrait logiquement être bon.

**Comment by felixgirault** [comment]
Ça marche merci.

Concernant mon commentaire https://github.com/empreinte-digitale/assistant-rgaa/issues/18#issuecomment-884882919, je me suis fait avoir par la présentation. Lorsqu'on active le test 9.1.1 on affiche pas les attributs `role`. Il serait peut-être judicieux de les afficher ?

![Capture d’écran_2021-07-22_14-53-25](https://user-images.githubusercontent.com/1544510/126642662-199143eb-40a1-42cd-80fd-dd92fdc14da0.png)

**Comment by luce-carevic** [comment]
> Ça marche merci.
> 
> Concernant mon commentaire [#18 (comment)](https://github.com/empreinte-digitale/assistant-rgaa/issues/18#issuecomment-884882919), je me suis fait avoir par la présentation. Lorsqu'on active le test 9.1.1 on affiche pas les attributs `role`. Il serait peut-être judicieux de les afficher ?
> 
> ![Capture d’écran_2021-07-22_14-53-25](https://user-images.githubusercontent.com/1544510/126642662-199143eb-40a1-42cd-80fd-dd92fdc14da0.png)

Oui, je pense !
