### ISSUE TITLE
Passage de la licence Ouverte 1.0 à une licence libre dédiée au logiciel

### ISSUE THREAD

**Issue by bzg** [empreinte-digitale/assistant-rgaa#2]
Bonjour, bravo pour cette mise à jour !

Je travaille pour la DINSIC comme référent logiciels libres.  Je voudrais proposer quelques évolutions sur ce dépôt au sujet de la licence.

- La licence d'origine, la licence Ouverte 1.0, n'est pas très adaptée : celle-ci est plutôt utilisée pour des publications de _données_ publiques, pas de code source.

- Quelle que soit la licence qui pourrait être choisie (une MIT/Expat, par exemple), il faudrait que celle-ci soit présente dans le dépôt sous forme de fichier `LICENSE.md`.

Voulez-vous que je fasse une PR pour ces changements ?

Merci d'avance !

**Comment by felixgirault** [comment]
Bonjour, merci pour votre commentaire !
Excusez-nous pour le temps de réponse, nous avons bien pris note du problème mais nous sommes encore en train de discuter de la meilleure licence à adopter (pour ce projet et d'autres). 
Ça risque de prendre encore un peu de temps mais on y travaille !
Je laisse l'issue ouverte en attendant.

**Comment by bzg** [comment]
Bonjour, j'espère que vous avez passé un bon été :)  Est-ce que vous avez du nouveau sur ce sujet ? Est-ce que je peux aider d'une façon ou d'une autre ?

**Comment by bzg** [comment]
Hello ! Petit bonjour pour donner suite à cette issue. Bonne journée !

**Comment by bzg** [comment]
Hello, de nouveau moi : désolé d'insister mais je voudrais savoir si quelqu'un s'occupe de ce dépôt.  Merci !

**Comment by felixgirault** [comment]
Bonjour, merci de votre rappel !
Nous avons finalement choisi une licence MIT pour ce dépôt.
