### ISSUE TITLE
Critère 10.1 - attribut size

### ISSUE THREAD

**Issue by stevenMouret** [empreinte-digitale/assistant-rgaa#20]
Il semble que l'attribut `size` ne soit pas pris en compte.

**Comment by felixgirault** [comment]
Bonjour,
On a corrigé les tests en se basant sur le glossaire, mais il semble qu'il y ait une différence de définition des balises et attributs entre le glossaire et la méthodologie de test en RGAA 4 (https://github.com/DISIC/RGAA/issues/84).
Nous allons peut-être faire une version intermédiaire qui corrige le comportement actuel, avant de tout reprendre pour coller au référentiel.
N'hésitez pas à mettre un message dans [l'issue RGAA 4](https://github.com/DISIC/RGAA/issues/84) pour appuyer la demande, elle n'a pas bougé depuis un an...

**Comment by stevenMouret** [comment]
Bonjour, merci pour la correction et merci pour la reprise de l'extension. J'ai fait un Up sur [l'issue #84 du RGAA 4](https://github.com/DISIC/RGAA/issues/84).
