### ISSUE TITLE
instructions manquantes dans test 7.2.2

### ISSUE THREAD

**Issue by acaodinsic** [empreinte-digitale/assistant-rgaa#23]
Les instructions sont manquantes pour le test 7.2.2
Il faudrait ajouter

1. Retrouver dans le document tous les éléments non textuels mis à jour par une fonctionnalité JavaScript.
2. Si l'élément non textuel a une alternative, vérifier que :
    1. L'alternative est mise à jour lorsque le contenu non textuel est mis à jour ;
    2. L'alternative mise à jour est pertinente.
3. Si c'est le cas, le test est validé.

**Comment by felixgirault** [comment]
Bonjour,
Merci de votre retour, une correction est prête, elle sera publiée bientôt dans une prochaine version https://github.com/empreinte-digitale/assistant-rgaa/pull/22

**Comment by felixgirault** [comment]
Bonjour @acaodinsic,
La version 1.2.1 disponible sur les stores embarque le correctif.
Je clos ce ticket mais n'hésitez pas à le réouvrir si nécessaire.
