### ISSUE TITLE
Mise à jour de l'entité Wikidata?

### ISSUE THREAD

**Issue by bzg** [empreinte-digitale/assistant-rgaa#25]
Bonjour, il existe une entité Wikidata pour l'Assistant RGAA: https://www.wikidata.org/wiki/Q98731896

Je maintiens à jour le Socle interministériel de logiciels libres et nous utilisons Wikidata pour récupérer des informations supplémentaires sur les logiciels référencés - comme le logo, l'URL du code source, de la documentation, etc.

La [fiche Assistant RGAA du SILL](https://sill.etalab.gouv.fr/fr/software?id=13) serait plus riche si l'entité Wikidata était maintenue à jour: pensez-vous pouvoir l'enrichir ?  Notamment pour le logo, le lien vers le code source et la documentation (la licence n'est pas récupérée depuis Wikidata).

Pour un exemple d'entité Wikidata très bien faite: https://www.wikidata.org/wiki/Q8038

Merci beaucoup !

**Comment by bzg** [comment]
Bonjour, je me permets une relance à ce sujet.  Merci !

**Comment by felixgirault** [comment]
Bonjour,
Désolé pour le temps de réponse, je viens de mettre à jour l'entité (l'ajout d'images est fastidieux :grimacing: ).
Est-ce que ça vous convient ?

**Comment by bzg** [comment]
Merci beaucoup !  J'ai mis la fiche SILL à jour : https://sill.etalab.gouv.fr/fr/software?id=13
