### ISSUE TITLE
Mettre à jour la licence sur Mozilla Addons

### ISSUE THREAD

**Issue by Altonss** [empreinte-digitale/assistant-rgaa#26]
La licence indiquée sur https://addons.mozilla.org/fr/firefox/addon/assistant-rgaa/ est "Tous droits réservés" alors que sur ce dépôt il s'agit de la licence MIT. Serait-il possible de rectifier cela?

**Comment by felixgirault** [comment]
Bonjour,
Merci de votre remarque, nous avons bien mis à jour la page :)
