### ISSUE TITLE
mise en évidence de la balise <big> dans le test 10.1.1

### ISSUE THREAD

**Issue by Migou** [empreinte-digitale/assistant-rgaa#27]
Bonjour,

La balise big n'est pas mise en évidence dans le test 10.1.1

Il faudrait la rajouter, n'est-ce pas ?

Un site pour tester : http://decode.ouvaton.org/

**Comment by ClementCousein** [comment]
Effectivement l'implémentation du test n'est pas bonne, j'ai ouvert une PR pour corriger le soucis.
