### ISSUE TITLE
Test 11.13.1 - élément injustement mis en avant

### ISSUE THREAD

**Issue by luce-carevic** [empreinte-digitale/assistant-rgaa#28]
Il y a des effets de bord et des éléments mis en avant.

![image](https://user-images.githubusercontent.com/6073336/137987731-b2c03d44-cac9-46bc-bb5b-f71cda715f8c.png)

Code de l'élément mis en avant : `<h2 id="home_form" class="title" tabindex="-1">Quels sont vos besoins en accessibilité numérique ?</h2>`

**Comment by ClementCousein** [comment]
Nous ne reproduisons pas le problème. 

Je ferme donc l'issue en l'absence de nouveaux éléments, merci d'en ré-ouvrir une autre si le problème persiste.
