### ISSUE TITLE
Attribut size pas remonté

### ISSUE THREAD

**Issue by luce-carevic** [empreinte-digitale/assistant-rgaa#31]
`<input data-drupal-selector="edit-dv" type="text" id="edit-dv" name="dv" value="" size="60" maxlength="6" class="form-text required form-field webform-block" required="required" aria-required="true">`

L'attribut size n'est pas relevé par l'Assistant sur l'input.

**Comment by sbonaventure** [comment]
C'est désormais corrigé depuis ce commit : https://github.com/empreinte-digitale/assistant-rgaa/commit/4d9daf79a975d0eb977716e9b9bdd08cbafe5657
