### ISSUE TITLE
Critère 6.2 : un lien est un élément a avec attribut href

### ISSUE THREAD

**Issue by juliemoynatPro** [empreinte-digitale/assistant-rgaa#42]
Lorsqu'on coche le critère 6.2, l'extension met en avant des soi-disant liens sans intitulé lorsqu'il s'agit d'un élément `a` sans attribut `href`. Cependant, un élément `a` n'est un lien que s'il a un attribut `href`. `<a name="truc"></a>` ou `<a id="truc"></a>` ne devraient pas être invalidés.

La note technique du critère le précise d'ailleurs :

>Une ancre n’est pas un lien même si pendant longtemps l’élément `<a>` a servi de support à cette technique. Elle n’est donc pas concernée par le présent critère.

**Comment by sbonaventure** [comment]
Tout à fait @juliemoynatPro !
